export const quotes = [
    "Keep calm and code on.",
    "Bugs are just misunderstood features.",
    "The cake is a lie.",
    "Eat, sleep, code, repeat.",
    "Coding is my cardio.",
    "Trust me, I'm a developer.",
    "To code or not to code.",
    "I turn coffee into code.",
    "Hello World, meet my keyboard.",
    "I write code. What's your superpower?",
    "First, solve the problem. Then, write the code.",
    "Programs must be written for people to read.",
    "It works on my machine.",
    "In code we trust.",
    "Keyboard warrior at your service.",
    "Whitespace matters. So do you.",
    "404: Motivation not found.",
    "If debugging is the process of removing bugs, then programming must be the process of putting them in.",
    "Life is short. Write clean code.",
    "Semicolons are my punctuation of choice.",
    "My code never has bugs. It just develops unexpected features.",
    "Version control saves friendships.",
    "You had me at 'Hello, World.'",
    "Home is where the Wi-Fi connects automatically.",
    "When in doubt, blame the compiler.",
    "Sleeping is for the weak. Or those who don't code.",
    "You can't spell 'developer' without 'dev'.",
    "The only constant in programming is change.",
    "I dream in code and cry in stack traces.",
    "There’s no place like 127.0.0.1.",
    "A day without code is like a day without coffee. Unacceptable.",
    "Ctrl + S is my reflex.",
    "Some people play games. I write them.",
    "I ship code, not excuses.",
    "I don't always test my code, but when I do, I do it in production.",
    "A commit a day keeps the bugs away.",
    "Git push, pray, repeat.",
    "I refactor, therefore I am.",
    "My love language is dark mode.",
    "Why write a sentence when you can write a function?",
    "Coding is the closest thing to real magic.",
    "Error is just another word for opportunity.",
    "Sometimes, I talk to my code. And sometimes, it talks back.",
    "The bug is not a bug, it's a feature.",
    "If code were poetry, I'd be Shakespeare.",
    "Don't touch my code unless you have snacks.",
    "I'm not arguing. I'm just explaining why I'm right.",
    "Stack Overflow is my spirit animal.",
    "Silence is golden – unless you forgot to log the error.",
    "Every keystroke is a tiny rebellion.",
    "Null is the void that stares back.",
    "I write bugs with style.",
    "Behind every line of code is a caffeine-powered human.",
    "Haters gonna hate, coders gonna code.",
    "No plan survives contact with the compiler.",
    "A good day starts with coffee and ends with a successful build.",
    "May your commits be clean and your merges conflict-free.",
    "You miss all the bugs you don’t test for.",
    "Syntax first, sanity later.",
    "Code like no one is watching. But comment like everyone is."
];