export const quotes = [
  'The sky isn\'t the limit. It\'s just the beginning.',
  'Life is like riding a bicycle. To keep your balance, you must keep moving.',
  'Dreams don\'t work unless you do.',
  'You don\'t find the light by avoiding the darkness.',
  'Stay curious, stay weird, stay wonderful.',
  'Coffee first. Schemes later.',
  'Sometimes the bravest thing you can do is get out of bed.',
  'The universe is under no obligation to make sense to you.',
  'Don\'t grow up. It\'s a trap.',
  'Zeni is somewhere coding and probably overthinking semicolons.',
  'Be the plot twist you wish to see in your story.',
  'Some days you tame the dragon. Some days the dragon eats you.',
  'Make it messy, then make it magic.',
  'You are the glitch in the simulation. Embrace it.',
  'Chaos is just another form of art.',
  'Reality is overrated. Code something better.',
  'If it scares you, it might be worth doing.',
  'Typing fast doesn\'t mean thinking fast.',
  'You were born to stand out, not fit in.',
  'No bugs. Just unexpected features.',
  'Take breaks. Even heroes need naps.',
  'You miss 100% of the typos you don\'t catch.',
  'Never trust a smiling compiler.',
  'Silence is golden. Unless you forgot a `console.log`.',
  'Every line of code is a tiny rebellion.',
  'You survived yesterday. You can wreck today.',
  'Legends aren\'t born. They hit backspace and try again.'
];
